### ISSUE TITLE
Incorrect plugin initialisation in usage

### ISSUE THREAD

**Issue by teehemkay** [gobblejs/gobble-postcss#4]
In usage:

`require( 'autoprefixer-core', { browsers: [ 'last 2 versions' ] }),`

should read

   `require( 'autoprefixer-core')({ browsers: [ 'last 2 versions' ] }),`

And  `autoprefixer-core` is deprecated in favour of  `autorprefixer`

**Comment by Rich-Harris** [comment]
Thanks, fixed!
